In [5]:
# https://splunktool.com/extract-features-and-labels-from-a-tensorflow-dataset

import tensorflow as tf
import numpy as np
# from tensorflow.keras import layers

import tensorflow_datasets as tfds

data = tfds.load("iris",split='train[:80%]', as_supervised=True)
ds = data.batch(10)
print(ds.element_spec)

# In case your tf.data.Dataset is batched, the following code will retrieve all the y labels:

y = np.concatenate([y  for x, y in ds], axis = 0)
print(y)

ds_one_hot = data.batch(10).map(lambda x, y: (x, tf.one_hot(y, depth=3)))
print(next(iter(ds_one_hot))[1])
print(ds_one_hot.element_spec)


(TensorSpec(shape=(None, 4), dtype=tf.float32, name=None), TensorSpec(shape=(None,), dtype=tf.int64, name=None))
[0 2 1 2 0 1 1 1 0 2 1 0 2 0 0 0 0 0 2 2 2 2 2 0 2 0 2 1 1 1 1 1 2 2 0 0 0
 0 1 0 0 1 0 1 0 2 0 0 1 2 1 0 0 1 0 1 1 1 2 0 0 1 2 0 0 1 2 2 1 2 2 2 0 2
 1 0 0 1 2 1 1 2 0 1 2 0 2 1 2 1 2 1 0 1 2 1 0 1 1 2 2 2 0 2 1 2 1 0 1 0 2
 2 0 2 0 1 2 0 2 1]
tf.Tensor(
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]], shape=(10, 3), dtype=float32)
(TensorSpec(shape=(None, 4), dtype=tf.float32, name=None), TensorSpec(shape=(None, 3), dtype=tf.float32, name=None))
