In [1]:
# http://man.hubwiz.com/docset/TensorFlow.docset/Contents/Resources/Documents/api_docs/python/tf/stack.html

import tensorflow as tf
import pandas as pd
import numpy as np
import sys, os, json
from pathlib import Path

print(tf.__version__)

x = tf.constant([1, 4])
y = tf.constant([2, 5])
z = tf.constant([3, 6])
w1 =tf.stack([x, y, z])  # [[1, 4], [2, 5], [3, 6]] (Pack along first dim.)
print("\nw1")
print(w1)
w1 = w1.numpy()
print("\nw2")
w2 = tf.stack([x, y, z], axis=1)  # [[1, 2, 3], [4, 5, 6]]
print(w2)



2.8.2

w1
tf.Tensor(
[[1 4]
 [2 5]
 [3 6]], shape=(3, 2), dtype=int32)

w2
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [4]:
# https://www.gcptutorials.com/article/how-to-use-map-function-with-tensorflow-datasets

# Create Tensor
tensor1 = tf.range(5)
  
#print(dir(tf.data.Dataset))
#Create dataset, this will return object of TensorSliceDataset
dataset = tf.data.Dataset.from_tensor_slices(tensor1)
print()
print(dataset.element_spec)
print("Original dataset")
for i in dataset:
    print(i)

# Transforming dataset items using map()
print()
print("dataset after applying map function")
dataset = dataset.map(lambda x : x*x*x)
for i in dataset:
    print(i)
  


TensorSpec(shape=(), dtype=tf.int32, name=None)
Original dataset
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)

dataset after applying map function
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(27, shape=(), dtype=int32)
tf.Tensor(64, shape=(), dtype=int32)


In [8]:
# https://colab.research.google.com/github/tfindiamooc/tfindiamooc.github.io/blob/master/colabs/csv.ipynb#scrollTo=sUtoed20cRJJ

# filepath = Path(features_dir, feature_set_fname)
filepath = "train_features.csv"
print()
print(f'\nPožymių masyvas iš:  {filepath}')
batch_size = 2
selected_features = ['label','RRl/RRr', '0', '1', '2']

data_frame = pd.read_csv(filepath)
print()
data_frame = data_frame[selected_features]
print(data_frame.head(20))


dt_train_raw = tf.data.experimental.make_csv_dataset(
    filepath,
    batch_size=batch_size, # Artificially small to make examples easier to show.
    select_columns=selected_features,
    label_name='label',
    num_epochs=1,
    ignore_errors=True,)
    
print(f'\ndt_train_raw.element_spec: {dt_train_raw.element_spec}')

print()
for batch, label in dt_train_raw.take(1):
    for key, value in batch.items():
      print(f"{key}: {value}")
    print()
    print(f"{'y'}: {label}")  

# print(batch)
# print(label)

# dt_single = dt_train_raw.get_single_element()
# print("\ndt_single")
# print(dt_single)

i = 0
for element in dt_train_raw.as_numpy_iterator():
  print("\n",i)
  i +=1
  print(element)

# Here's a simple function that will pack together all the columns:
def pack(features, label):
    return tf.stack(list(features.values()), axis=-1), label

# Apply this to each element of the dataset:
dt_train = dt_train_raw.map(pack)

print(f'\ndt_train.element_spec: {dt_train.element_spec}')

for features, labels in dt_train.take(1):
    print()
    print(features.numpy())
    print()
    print(labels.numpy())

print()
for features, labels in dt_train_raw.take(1):
    print('\nfeatures:')
    print(features)
    print('\nlabels:')
    print(labels)
    print('\npack:')
    print(pack(features, label))



Požymių masyvas iš:  train_features.csv

    label   RRl/RRr         0         1         2
0       0  1.010204  1.108669  1.113325  1.119979
1       0  1.010309  1.092491  1.097881  1.103802
2       0  0.979798  0.951143  0.955648  0.961126
3       0  1.020619  0.978220  0.981224  0.986719
4       0  1.000000  1.014153  1.021665  1.027687
5       0  0.989796  1.133533  1.152454  1.150649
6       0  1.000000  1.039528  1.045420  1.052284
7       0  1.000000  0.944671  0.940397  0.935575
8       0  0.989899  1.028799  1.026006  1.027148
9       0  1.000000  0.693991  0.707474  0.719160
10      0  0.970588  0.652779  0.671098  0.684211
11      0  0.980769  0.732309  0.732309  0.731145
12      0  0.971963  0.453699  0.465116  0.476454
13      0  0.990741  0.624169  0.636581  0.649408
14      0  0.981818  0.610034  0.615203  0.619226
15      0  1.009174  0.367188  0.372000  0.378970
16      0  1.018692  0.652098  0.669057  0.684660
17      0  1.009434  0.768582  0.769086  0.784060
18     